/** Official Valve CN client hero names (schinese name_loc from dota2.com datafeed). */

import type { OpenDotaHero } from "./types";

export const HERO_NAME_CN_BY_ID: Record<number, string> = {
  1: "敌法师",
  2: "斧王",
  3: "祸乱之源",
  4: "血魔",
  5: "水晶室女",
  6: "卓尔游侠",
  7: "撼地者",
  8: "主宰",
  9: "米拉娜",
  10: "变体精灵",
  11: "影魔",
  12: "幻影长矛手",
  13: "帕克",
  14: "帕吉",
  15: "雷泽",
  16: "沙王",
  17: "风暴之灵",
  18: "斯温",
  19: "小小",
  20: "复仇之魂",
  21: "风行者",
  22: "宙斯",
  23: "昆卡",
  25: "莉娜",
  26: "莱恩",
  27: "暗影萨满",
  28: "斯拉达",
  29: "潮汐猎人",
  30: "巫医",
  31: "巫妖",
  32: "力丸",
  33: "谜团",
  34: "修补匠",
  35: "狙击手",
  36: "瘟疫法师",
  37: "术士",
  38: "兽王",
  39: "痛苦女王",
  40: "剧毒术士",
  41: "虚空假面",
  42: "冥魂大帝",
  43: "死亡先知",
  44: "幻影刺客",
  45: "帕格纳",
  46: "圣堂刺客",
  47: "冥界亚龙",
  48: "露娜",
  49: "龙骑士",
  50: "戴泽",
  51: "发条技师",
  52: "拉席克",
  53: "自然先知",
  54: "噬魂鬼",
  55: "黑暗贤者",
  56: "克林克兹",
  57: "全能骑士",
  58: "魅惑魔女",
  59: "哈斯卡",
  60: "暗夜魔王",
  61: "育母蜘蛛",
  62: "赏金猎人",
  63: "编织者",
  64: "杰奇洛",
  65: "蝙蝠骑士",
  66: "陈",
  67: "幽鬼",
  68: "远古冰魄",
  69: "末日使者",
  70: "熊战士",
  71: "裂魂人",
  72: "矮人直升机",
  73: "炼金术士",
  74: "祈求者",
  75: "沉默术士",
  76: "殁境神蚀者",
  77: "狼人",
  78: "酒仙",
  79: "暗影恶魔",
  80: "独行德鲁伊",
  81: "混沌骑士",
  82: "米波",
  83: "树精卫士",
  84: "食人魔魔法师",
  85: "不朽尸王",
  86: "拉比克",
  87: "干扰者",
  88: "司夜刺客",
  89: "娜迦海妖",
  90: "光之守卫",
  91: "艾欧",
  92: "维萨吉",
  93: "斯拉克",
  94: "美杜莎",
  95: "巨魔战将",
  96: "半人马战行者",
  97: "马格纳斯",
  98: "伐木机",
  99: "钢背兽",
  100: "巨牙海民",
  101: "天怒法师",
  102: "亚巴顿",
  103: "上古巨神",
  104: "军团指挥官",
  105: "工程师",
  106: "灰烬之灵",
  107: "大地之灵",
  108: "孽主",
  109: "恐怖利刃",
  110: "凤凰",
  111: "神谕者",
  112: "寒冬飞龙",
  113: "天穹守望者",
  114: "齐天大圣",
  119: "邪影芳灵",
  120: "石鳞剑士",
  121: "天涯墨客",
  123: "森海飞霞",
  126: "虚无之灵",
  128: "电炎绝手",
  129: "玛尔斯",
  131: "百戏大王",
  135: "破晓辰星",
  136: "玛西",
  137: "獸",
  138: "琼英碧灵",
  145: "凯",
  155: "朗戈",
};

export const HERO_NAME_CN_BY_INTERNAL: Record<string, string> = {
  "npc_dota_hero_abaddon": "亚巴顿",
  "npc_dota_hero_abyssal_underlord": "孽主",
  "npc_dota_hero_alchemist": "炼金术士",
  "npc_dota_hero_ancient_apparition": "远古冰魄",
  "npc_dota_hero_antimage": "敌法师",
  "npc_dota_hero_arc_warden": "天穹守望者",
  "npc_dota_hero_axe": "斧王",
  "npc_dota_hero_bane": "祸乱之源",
  "npc_dota_hero_batrider": "蝙蝠骑士",
  "npc_dota_hero_beastmaster": "兽王",
  "npc_dota_hero_bloodseeker": "血魔",
  "npc_dota_hero_bounty_hunter": "赏金猎人",
  "npc_dota_hero_brewmaster": "酒仙",
  "npc_dota_hero_bristleback": "钢背兽",
  "npc_dota_hero_broodmother": "育母蜘蛛",
  "npc_dota_hero_centaur": "半人马战行者",
  "npc_dota_hero_chaos_knight": "混沌骑士",
  "npc_dota_hero_chen": "陈",
  "npc_dota_hero_clinkz": "克林克兹",
  "npc_dota_hero_crystal_maiden": "水晶室女",
  "npc_dota_hero_dark_seer": "黑暗贤者",
  "npc_dota_hero_dark_willow": "邪影芳灵",
  "npc_dota_hero_dawnbreaker": "破晓辰星",
  "npc_dota_hero_dazzle": "戴泽",
  "npc_dota_hero_death_prophet": "死亡先知",
  "npc_dota_hero_disruptor": "干扰者",
  "npc_dota_hero_doom_bringer": "末日使者",
  "npc_dota_hero_dragon_knight": "龙骑士",
  "npc_dota_hero_drow_ranger": "卓尔游侠",
  "npc_dota_hero_earth_spirit": "大地之灵",
  "npc_dota_hero_earthshaker": "撼地者",
  "npc_dota_hero_elder_titan": "上古巨神",
  "npc_dota_hero_ember_spirit": "灰烬之灵",
  "npc_dota_hero_enchantress": "魅惑魔女",
  "npc_dota_hero_enigma": "谜团",
  "npc_dota_hero_faceless_void": "虚空假面",
  "npc_dota_hero_furion": "自然先知",
  "npc_dota_hero_grimstroke": "天涯墨客",
  "npc_dota_hero_gyrocopter": "矮人直升机",
  "npc_dota_hero_hoodwink": "森海飞霞",
  "npc_dota_hero_huskar": "哈斯卡",
  "npc_dota_hero_invoker": "祈求者",
  "npc_dota_hero_jakiro": "杰奇洛",
  "npc_dota_hero_juggernaut": "主宰",
  "npc_dota_hero_keeper_of_the_light": "光之守卫",
  "npc_dota_hero_kez": "凯",
  "npc_dota_hero_kunkka": "昆卡",
  "npc_dota_hero_largo": "朗戈",
  "npc_dota_hero_legion_commander": "军团指挥官",
  "npc_dota_hero_leshrac": "拉席克",
  "npc_dota_hero_lich": "巫妖",
  "npc_dota_hero_life_stealer": "噬魂鬼",
  "npc_dota_hero_lina": "莉娜",
  "npc_dota_hero_lion": "莱恩",
  "npc_dota_hero_lone_druid": "独行德鲁伊",
  "npc_dota_hero_luna": "露娜",
  "npc_dota_hero_lycan": "狼人",
  "npc_dota_hero_magnataur": "马格纳斯",
  "npc_dota_hero_marci": "玛西",
  "npc_dota_hero_mars": "玛尔斯",
  "npc_dota_hero_medusa": "美杜莎",
  "npc_dota_hero_meepo": "米波",
  "npc_dota_hero_mirana": "米拉娜",
  "npc_dota_hero_monkey_king": "齐天大圣",
  "npc_dota_hero_morphling": "变体精灵",
  "npc_dota_hero_muerta": "琼英碧灵",
  "npc_dota_hero_naga_siren": "娜迦海妖",
  "npc_dota_hero_necrolyte": "瘟疫法师",
  "npc_dota_hero_nevermore": "影魔",
  "npc_dota_hero_night_stalker": "暗夜魔王",
  "npc_dota_hero_nyx_assassin": "司夜刺客",
  "npc_dota_hero_obsidian_destroyer": "殁境神蚀者",
  "npc_dota_hero_ogre_magi": "食人魔魔法师",
  "npc_dota_hero_omniknight": "全能骑士",
  "npc_dota_hero_oracle": "神谕者",
  "npc_dota_hero_pangolier": "石鳞剑士",
  "npc_dota_hero_phantom_assassin": "幻影刺客",
  "npc_dota_hero_phantom_lancer": "幻影长矛手",
  "npc_dota_hero_phoenix": "凤凰",
  "npc_dota_hero_primal_beast": "獸",
  "npc_dota_hero_puck": "帕克",
  "npc_dota_hero_pudge": "帕吉",
  "npc_dota_hero_pugna": "帕格纳",
  "npc_dota_hero_queenofpain": "痛苦女王",
  "npc_dota_hero_rattletrap": "发条技师",
  "npc_dota_hero_razor": "雷泽",
  "npc_dota_hero_riki": "力丸",
  "npc_dota_hero_ringmaster": "百戏大王",
  "npc_dota_hero_rubick": "拉比克",
  "npc_dota_hero_sand_king": "沙王",
  "npc_dota_hero_shadow_demon": "暗影恶魔",
  "npc_dota_hero_shadow_shaman": "暗影萨满",
  "npc_dota_hero_shredder": "伐木机",
  "npc_dota_hero_silencer": "沉默术士",
  "npc_dota_hero_skeleton_king": "冥魂大帝",
  "npc_dota_hero_skywrath_mage": "天怒法师",
  "npc_dota_hero_slardar": "斯拉达",
  "npc_dota_hero_slark": "斯拉克",
  "npc_dota_hero_snapfire": "电炎绝手",
  "npc_dota_hero_sniper": "狙击手",
  "npc_dota_hero_spectre": "幽鬼",
  "npc_dota_hero_spirit_breaker": "裂魂人",
  "npc_dota_hero_storm_spirit": "风暴之灵",
  "npc_dota_hero_sven": "斯温",
  "npc_dota_hero_techies": "工程师",
  "npc_dota_hero_templar_assassin": "圣堂刺客",
  "npc_dota_hero_terrorblade": "恐怖利刃",
  "npc_dota_hero_tidehunter": "潮汐猎人",
  "npc_dota_hero_tinker": "修补匠",
  "npc_dota_hero_tiny": "小小",
  "npc_dota_hero_treant": "树精卫士",
  "npc_dota_hero_troll_warlord": "巨魔战将",
  "npc_dota_hero_tusk": "巨牙海民",
  "npc_dota_hero_undying": "不朽尸王",
  "npc_dota_hero_ursa": "熊战士",
  "npc_dota_hero_vengefulspirit": "复仇之魂",
  "npc_dota_hero_venomancer": "剧毒术士",
  "npc_dota_hero_viper": "冥界亚龙",
  "npc_dota_hero_visage": "维萨吉",
  "npc_dota_hero_void_spirit": "虚无之灵",
  "npc_dota_hero_warlock": "术士",
  "npc_dota_hero_weaver": "编织者",
  "npc_dota_hero_windrunner": "风行者",
  "npc_dota_hero_winter_wyvern": "寒冬飞龙",
  "npc_dota_hero_wisp": "艾欧",
  "npc_dota_hero_witch_doctor": "巫医",
  "npc_dota_hero_zuus": "宙斯",
};

export function heroNameCn(heroId: number, internalName?: string, fallback?: string): string {
  return (
    HERO_NAME_CN_BY_ID[heroId] ??
    (internalName ? HERO_NAME_CN_BY_INTERNAL[internalName] : undefined) ??
    fallback ??
    `英雄 ${heroId}`
  );
}

/** Build static hero list (id → internal name) so SSR never waits on OpenDota /heroes. */
export function getStaticHeroes(): OpenDotaHero[] {
  const cnToInternal = new Map<string, string>();
  for (const [internal, cn] of Object.entries(HERO_NAME_CN_BY_INTERNAL)) {
    cnToInternal.set(cn, internal);
  }
  return Object.entries(HERO_NAME_CN_BY_ID).map(([idStr, cn]) => {
    const id = Number(idStr);
    const name = cnToInternal.get(cn) ?? `npc_dota_hero_id_${id}`;
    return {
      id,
      name,
      localized_name: cn,
      primary_attr: "",
      attack_type: "",
      roles: [] as string[],
    };
  });
}
